// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommitWire.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SourceCode.Chasm.IO.Proto.Wire {

  /// <summary>Holder for reflection information generated from CommitWire.proto</summary>
  public static partial class CommitWireReflection {

    #region Descriptor
    /// <summary>File descriptor for CommitWire.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommitWireReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBDb21taXRXaXJlLnByb3RvGg90aW1lc3RhbXAucHJvdG8aDlNoYTFXaXJl",
            "LnByb3RvIn0KCkNvbW1pdFdpcmUSGgoHUGFyZW50cxgBIAMoCzIJLlNoYTFX",
            "aXJlEhkKBlRyZWVJZBgCIAEoCzIJLlNoYTFXaXJlEicKA1V0YxgDIAEoCzIa",
            "Lmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASDwoHTWVzc2FnZRgEIAEoCUIh",
            "qgIeU291cmNlQ29kZS5DaGFzbS5JTy5Qcm90by5XaXJlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::SourceCode.Chasm.IO.Proto.Wire.Sha1WireReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SourceCode.Chasm.IO.Proto.Wire.CommitWire), global::SourceCode.Chasm.IO.Proto.Wire.CommitWire.Parser, new[]{ "Parents", "TreeId", "Utc", "Message" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CommitWire : pb::IMessage<CommitWire> {
    private static readonly pb::MessageParser<CommitWire> _parser = new pb::MessageParser<CommitWire>(() => new CommitWire());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CommitWire> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SourceCode.Chasm.IO.Proto.Wire.CommitWireReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommitWire() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommitWire(CommitWire other) : this() {
      parents_ = other.parents_.Clone();
      TreeId = other.treeId_ != null ? other.TreeId.Clone() : null;
      Utc = other.utc_ != null ? other.Utc.Clone() : null;
      message_ = other.message_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommitWire Clone() {
      return new CommitWire(this);
    }

    /// <summary>Field number for the "Parents" field.</summary>
    public const int ParentsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::SourceCode.Chasm.IO.Proto.Wire.Sha1Wire> _repeated_parents_codec
        = pb::FieldCodec.ForMessage(10, global::SourceCode.Chasm.IO.Proto.Wire.Sha1Wire.Parser);
    private readonly pbc::RepeatedField<global::SourceCode.Chasm.IO.Proto.Wire.Sha1Wire> parents_ = new pbc::RepeatedField<global::SourceCode.Chasm.IO.Proto.Wire.Sha1Wire>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SourceCode.Chasm.IO.Proto.Wire.Sha1Wire> Parents {
      get { return parents_; }
    }

    /// <summary>Field number for the "TreeId" field.</summary>
    public const int TreeIdFieldNumber = 2;
    private global::SourceCode.Chasm.IO.Proto.Wire.Sha1Wire treeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SourceCode.Chasm.IO.Proto.Wire.Sha1Wire TreeId {
      get { return treeId_; }
      set {
        treeId_ = value;
      }
    }

    /// <summary>Field number for the "Utc" field.</summary>
    public const int UtcFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp utc_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Utc {
      get { return utc_; }
      set {
        utc_ = value;
      }
    }

    /// <summary>Field number for the "Message" field.</summary>
    public const int MessageFieldNumber = 4;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CommitWire);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CommitWire other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!parents_.Equals(other.parents_)) return false;
      if (!object.Equals(TreeId, other.TreeId)) return false;
      if (!object.Equals(Utc, other.Utc)) return false;
      if (Message != other.Message) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= parents_.GetHashCode();
      if (treeId_ != null) hash ^= TreeId.GetHashCode();
      if (utc_ != null) hash ^= Utc.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      parents_.WriteTo(output, _repeated_parents_codec);
      if (treeId_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TreeId);
      }
      if (utc_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Utc);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Message);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += parents_.CalculateSize(_repeated_parents_codec);
      if (treeId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TreeId);
      }
      if (utc_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Utc);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CommitWire other) {
      if (other == null) {
        return;
      }
      parents_.Add(other.parents_);
      if (other.treeId_ != null) {
        if (treeId_ == null) {
          treeId_ = new global::SourceCode.Chasm.IO.Proto.Wire.Sha1Wire();
        }
        TreeId.MergeFrom(other.TreeId);
      }
      if (other.utc_ != null) {
        if (utc_ == null) {
          utc_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Utc.MergeFrom(other.Utc);
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            parents_.AddEntriesFrom(input, _repeated_parents_codec);
            break;
          }
          case 18: {
            if (treeId_ == null) {
              treeId_ = new global::SourceCode.Chasm.IO.Proto.Wire.Sha1Wire();
            }
            input.ReadMessage(treeId_);
            break;
          }
          case 26: {
            if (utc_ == null) {
              utc_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(utc_);
            break;
          }
          case 34: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
