// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommitRefWire.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SourceCode.Chasm.IO.Proto.Wire {

  /// <summary>Holder for reflection information generated from CommitRefWire.proto</summary>
  public static partial class CommitRefWireReflection {

    #region Descriptor
    /// <summary>File descriptor for CommitRefWire.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommitRefWireReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNDb21taXRSZWZXaXJlLnByb3RvGg5TaGExV2lyZS5wcm90byIsCg1Db21t",
            "aXRSZWZXaXJlEhsKCENvbW1pdElkGAEgASgLMgkuU2hhMVdpcmVCIaoCHlNv",
            "dXJjZUNvZGUuQ2hhc20uSU8uUHJvdG8uV2lyZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SourceCode.Chasm.IO.Proto.Wire.Sha1WireReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SourceCode.Chasm.IO.Proto.Wire.CommitRefWire), global::SourceCode.Chasm.IO.Proto.Wire.CommitRefWire.Parser, new[]{ "CommitId" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CommitRefWire : pb::IMessage<CommitRefWire> {
    private static readonly pb::MessageParser<CommitRefWire> _parser = new pb::MessageParser<CommitRefWire>(() => new CommitRefWire());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CommitRefWire> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SourceCode.Chasm.IO.Proto.Wire.CommitRefWireReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommitRefWire() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommitRefWire(CommitRefWire other) : this() {
      CommitId = other.commitId_ != null ? other.CommitId.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommitRefWire Clone() {
      return new CommitRefWire(this);
    }

    /// <summary>Field number for the "CommitId" field.</summary>
    public const int CommitIdFieldNumber = 1;
    private global::SourceCode.Chasm.IO.Proto.Wire.Sha1Wire commitId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SourceCode.Chasm.IO.Proto.Wire.Sha1Wire CommitId {
      get { return commitId_; }
      set {
        commitId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CommitRefWire);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CommitRefWire other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CommitId, other.CommitId)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (commitId_ != null) hash ^= CommitId.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (commitId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CommitId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (commitId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CommitId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CommitRefWire other) {
      if (other == null) {
        return;
      }
      if (other.commitId_ != null) {
        if (commitId_ == null) {
          commitId_ = new global::SourceCode.Chasm.IO.Proto.Wire.Sha1Wire();
        }
        CommitId.MergeFrom(other.CommitId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (commitId_ == null) {
              commitId_ = new global::SourceCode.Chasm.IO.Proto.Wire.Sha1Wire();
            }
            input.ReadMessage(commitId_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
