
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.0.0
//   File : CommitWire_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace SourceCode.Chasm.IO.Bond.Wire
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.0.0")]
    public partial class CommitWire
    {
        [global::Bond.Id(1)]
        public List<Sha1Wire> Parents { get; set; }

        [global::Bond.Id(2)]
        public Sha1Wire TreeId { get; set; }

        [global::Bond.Id(3), global::Bond.Type(typeof(long))]
        public System.DateTime CommitUtc { get; set; }

        [global::Bond.Id(4), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string CommitMessage { get; set; }

        public CommitWire()
            : this("SourceCode.Chasm.IO.Bond.Wire.CommitWire", "CommitWire")
        {}

        protected CommitWire(string fullName, string name)
        {
            TreeId = new Sha1Wire();
            CommitUtc = new System.DateTime();
        }
    }
} // SourceCode.Chasm.IO.Bond.Wire
