
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.0.0
//   File : CommitRefWire_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace SourceCode.Chasm.IO.Bond.Wire
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.0.0")]
    public partial class CommitRefWire
    {
        [global::Bond.Id(1)]
        public Sha1Wire CommitId { get; set; }

        public CommitRefWire()
            : this("SourceCode.Chasm.IO.Bond.Wire.CommitRefWire", "CommitRefWire")
        {}

        protected CommitRefWire(string fullName, string name)
        {
            CommitId = new Sha1Wire();
        }
    }
} // SourceCode.Chasm.IO.Bond.Wire
