
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.0.0
//   File : TreeWire_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace SourceCode.Chasm.IO.Bond.Wire
{
    using System.Collections.Generic;

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.0.0")]
    public enum NodeKindWire
    {
        None = unchecked((int)0),
        Commit = unchecked((int)1),
        Tree = unchecked((int)2),
        Blob = unchecked((int)3),
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.0.0")]
    public partial class TreeWireNode
    {
        [global::Bond.Id(1)]
        public string Name { get; set; }

        [global::Bond.Id(2)]
        public NodeKindWire Kind { get; set; }

        [global::Bond.Id(3)]
        public Sha1Wire NodeId { get; set; }

        public TreeWireNode()
            : this("SourceCode.Chasm.IO.Bond.Wire.TreeWireNode", "TreeWireNode")
        {}

        protected TreeWireNode(string fullName, string name)
        {
            Name = "";
            Kind = NodeKindWire.None;
            NodeId = new Sha1Wire();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.0.0")]
    public partial class TreeWire
    {
        [global::Bond.Id(1)]
        public List<TreeWireNode> Nodes { get; set; }

        public TreeWire()
            : this("SourceCode.Chasm.IO.Bond.Wire.TreeWire", "TreeWire")
        {}

        protected TreeWire(string fullName, string name)
        {
            Nodes = new List<TreeWireNode>();
        }
    }
} // SourceCode.Chasm.IO.Bond.Wire
